name: bibis
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - biopython=1.78=py310h7f8727e_0
  - blas=1.0=mkl
  - bottleneck=1.3.7=py310ha9d4c09_0
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.3.11=h06a4308_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - et_xmlfile=1.1.0=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - joblib=1.2.0=py310h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libllvm14=14.0.6=hdb19cb5_3
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - llvmlite=0.42.0=py310h6a678d5_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - ncurses=6.4=h6a678d5_0
  - numba=0.59.0=py310h6a678d5_0
  - numexpr=2.8.7=py310h85018f9_0
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openpyxl=3.0.10=py310h5eee18b_0
  - openssl=3.0.13=h7f8727e_0
  - pandas=2.1.4=py310h1128e8f_0
  - parse=1.20.1=pyhd8ed1ab_0
  - pip=23.3.1=py310h06a4308_0
  - python=3.10.13=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytz=2023.3.post1=py310h06a4308_0
  - readline=8.2=h5eee18b_0
  - scikit-learn=1.3.0=py310h1128e8f_1
  - scipy=1.12.0=py310h5f9d8c6_0
  - setuptools=68.2.2=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - tqdm=4.66.2=pyhd8ed1ab_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - cffi==1.16.0
    - jinja2==3.1.3
    - markupsafe==2.1.5
    - pycparser==2.21
    - rpy2==3.5.15
    - tzlocal==5.2
